### ISSUE TITLE
Image operating system mismatch

### ISSUE THREAD

**Issue by trevor-viljoen** [openshift/compliance-operator#185]
I'm having trouble getting the operator up and running. It fails to pull quay.io/compliance-operator/compliance-operator. If I describe a pod it says: 
```
Failed to pull image "quay.io/compliance-operator/compliance-operator": rpc error: code = Unknown desc = Image operating system mismatch: image uses "", expecting "linux"
```

```
» oc get pods
NAME                                   READY   STATUS             RESTARTS   AGE
compliance-operator-85c8757fb8-6wmrw   0/1     ImagePullBackOff   0          3m47s
compliance-operator-85c8757fb8-nnmnq   0/1     ImagePullBackOff   0          18m
compliance-operator-85c8757fb8-v55ln   0/1     ImagePullBackOff   0          18m
```

**Comment by trevor-viljoen** [comment]
It appears the operator chose a master node to run on which has the `NoSchedule` taint applied.

**Comment by trevor-viljoen** [comment]
Maybe related to containers/buildah#2225

**Comment by JAORMX** [comment]
> Maybe related to [containers/buildah#2225](https://github.com/containers/buildah/issues/2225)

It sure looks related. We did apply tolerations to the master taints though,  you can check that with `oc get deployment <deployment name> -o yaml`or `oc describe deployment <deployment name>`.

**Comment by JAORMX** [comment]
Also, could you mention how you deployed?

**Comment by jhrozek** [comment]
On Wed, Mar 18, 2020 at 11:54:55PM -0700, Juan Osorio Robles wrote:
> Also, could you mention how you deployed?

By the way, I have hit this issue yesterday as well while working on the
file-integrity-operator. But, I only hit the issue when using the
"semi-official" images from quay.io. Everything worked fine for me when
I built my own images using "make image-to-cluster".

I don't know what might be the root cause, though.

**Comment by trevor-viljoen** [comment]
> Note that we're using podman to build these images. Any idea in what version of podman has this been fixed? 

containers/libpod#5503 has some more information.  We are running OCP `4.3.5`, `podman version 1.6.4`, released on Dec 11, 2019. Current version looks like `1.8.2-RC1`. 

According to this [comment](https://github.com/cloudfoundry-incubator/kubecf/issues/491#issuecomment-600274366), it looks like there was a check added for OS match. In the past not setting the OS was fine. 

It looks like the ability add the os and arch of the image using overrides from the commandline was added with this PR https://github.com/containers/libpod/pull/5508 to fix this issue in libpod/podman (v1.8.2-RC1).

> Also, could you mention how you deployed?

@JAORMX I followed the `README` and used the quay.io images.
```$ (clone repo)
$ oc create -f deploy/ns.yaml
$ for f in $(ls -1 deploy/crds/*crd.yaml); do oc create -f $f; done
$ oc create -f deploy/
```
Then, created a `compliancesuite` instance.

**Comment by JAORMX** [comment]
I pushed to quay again with the latest flag; did it help?

**Comment by trevor-viljoen** [comment]
I deleted the deployment and re-applied the operator, but I still see: ```
11s         Warning   Failed              pod/compliance-operator-85c8757fb8-hgvbp    Failed to pull image "quay.io/compliance-operator/compliance-operator": rpc error: code = Unknown desc = Image operating system mismatch: image uses "", expecting "linux"
```

**Comment by trevor-viljoen** [comment]
`podman inspect quay.io/container-operator/container-operator` shows `Os` to be `""`.

**Comment by trevor-viljoen** [comment]
```json
[
    {
        "Id": "b1ce8352bcd7897b38d9f3a084fce5feb5fedbc5f7a837adfc6fed01133de66d",
        "Digest": "sha256:e8571c26eb476efa09f25005117b9ef253911231b3a4f9d3a0978771cb579d61",
        "RepoTags": [
            "quay.io/compliance-operator/compliance-operator:latest"
        ],
        "RepoDigests": [
            "quay.io/compliance-operator/compliance-operator@sha256:e8571c26eb476efa09f25005117b9ef253911231b3a4f9d3a0978771cb579d61"
        ],
        "Parent": "",
        "Comment": "Imported from -",
        "Created": "2020-03-19T17:13:48.45786547Z",
        "Config": {
            "User": "1001",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "container=oci",
                "OPERATOR=/usr/local/bin/compliance-operator",
                "USER_UID=1001",
                "USER_NAME=compliance-operator"
            ],
            "Entrypoint": [
                "/usr/local/bin/entrypoint"
            ],
            "Labels": {
                "architecture": "x86_64",
                "authoritative-source-url": "registry.access.redhat.com",
                "build-date": "2020-03-02T17:49:30.347810",
                "com.redhat.build-host": "cpt-1006.osbs.prod.upshift.rdu2.redhat.com",
                "com.redhat.component": "ubi8-minimal-container",
                "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
                "description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
                "distribution-scope": "public",
                "io.k8s.description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
                "io.k8s.display-name": "Red Hat Universal Base Image 8 Minimal",
                "io.openshift.expose-services": "",
                "io.openshift.tags": "minimal rhel8",
                "maintainer": "Red Hat, Inc.",
                "name": "ubi8-minimal",
                "release": "407",
                "summary": "Provides the latest release of the minimal Red Hat Universal Base Image 8.",
                "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.1-407",
                "vcs-ref": "8c3c7acc321ed054dded6e6e13b5c09c043f42dc",
                "vcs-type": "git",
                "vendor": "Red Hat, Inc.",
                "version": "8.1"
            }
        },
        "Version": "",
        "Author": "",
        "Architecture": "",
        "Os": "",
        "Size": 156403824,
        "VirtualSize": 156403824,
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/containers/storage/overlay/a447f20adfda082c1d60e802b26a347417be72cd6c36986b15fe973b743ad8e7/diff:/var/lib/containers/storage/overlay/b14c549e65a22d476a52feb45729d84c1474edf536188529b6a3292e1725874c/diff:/var/lib/containers/storage/overlay/102cf125ce193c28f37362f8d8793edba0e52b662635bc17be8ffb04c85d9905/diff:/var/lib/containers/storage/overlay/b76aa58f4c23d3f335141fec3899bee485f0db24cdf82a95d334bee62e70e38b/diff",
                "UpperDir": "/var/lib/containers/storage/overlay/68bbb251f5f89fb6ce8a731b4b90429ead0398905169feceda30dd79c7795b85/diff",
                "WorkDir": "/var/lib/containers/storage/overlay/68bbb251f5f89fb6ce8a731b4b90429ead0398905169feceda30dd79c7795b85/work"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "",
                "",
                "",
                "",
                ""
            ]
        },
        "Labels": {
            "architecture": "x86_64",
            "authoritative-source-url": "registry.access.redhat.com",
            "build-date": "2020-03-02T17:49:30.347810",
            "com.redhat.build-host": "cpt-1006.osbs.prod.upshift.rdu2.redhat.com",
            "com.redhat.component": "ubi8-minimal-container",
            "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
            "description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
            "distribution-scope": "public",
            "io.k8s.description": "The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.",
            "io.k8s.display-name": "Red Hat Universal Base Image 8 Minimal",
            "io.openshift.expose-services": "",
            "io.openshift.tags": "minimal rhel8",
            "maintainer": "Red Hat, Inc.",
            "name": "ubi8-minimal",
            "release": "407",
            "summary": "Provides the latest release of the minimal Red Hat Universal Base Image 8.",
            "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8-minimal/images/8.1-407",
            "vcs-ref": "8c3c7acc321ed054dded6e6e13b5c09c043f42dc",
            "vcs-type": "git",
            "vendor": "Red Hat, Inc.",
            "version": "8.1"
        },
        "Annotations": {},
        "ManifestType": "application/vnd.docker.distribution.manifest.v1+prettyjws",
        "User": "1001",
        "History": [
            {
                "created": "2020-03-02T17:49:40.443965377Z",
                "comment": "Imported from -"
            },
            {
                "created": "2020-03-02T17:49:48.941892Z"
            },
            {
                "created": "2020-03-19T13:02:37.234388333Z",
                "created_by": "/bin/sh -c #(nop) ENV OPERATOR=/usr/local/bin/compliance-operator     USER_UID=1001     USER_NAME=compliance-operator",
                "empty_layer": true
            },
            {
                "created": "2020-03-19T17:13:43.324580451Z",
                "created_by": "/bin/sh -c #(nop) COPY file:acf71154fd649c1e38d6f46256d4e3960f4ea49da8a90de9233fbe5689bfb613 in ${OPERATOR} "
            },
            {
                "created": "2020-03-19T17:13:45.930859864Z",
                "created_by": "/bin/sh -c #(nop) COPY dir:f680e71a405dac0688f4c0632a66abc1eed5757af8b328e1d16a23bfb1e6bcb3 in /usr/local/bin "
            },
            {
                "created": "2020-03-19T17:13:47.148610923Z",
                "created_by": "/bin/sh -c  /usr/local/bin/user_setup"
            },
            {
                "created": "2020-03-19T17:13:48.267161046Z",
                "created_by": "/bin/sh -c #(nop) ENTRYPOINT [\"/usr/local/bin/entrypoint\"]",
                "empty_layer": true
            },
            {
                "created": "2020-03-19T17:13:48.45786547Z",
                "empty_layer": true
            }
        ],
        "NamesHistory": []
    }
]

**Comment by jhrozek** [comment]
FWIW, I pushed new images into quay.io using an older version of podman (1.8.0) so the images should now be usable until we figure out a more systematic solution.

**Comment by trevor-viljoen** [comment]
@jhrozek That looks to have successfully deployed the operator pods, but when I check the `compliancesuite`, the status for both node groups is `LAUNCHING`.

**Comment by trevor-viljoen** [comment]
What I'm seeing now is unrelated to this issue. So this can be closed unless you want to leave it open to document the more systematic solution.
